name: GitHub Auto Buider For Blog

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 21 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: "10.x"

      - name: Clone themes
        run: |
          git clone -b dev https://github.com/forsigner/fexo.git themes/fexo          

      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v1
        with:
          path: .npm
          key: ${{runner.OS}}-npm-caches-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install
          npm audit fix          

      - name: Generate files
        run: |
          hexo clean && hexo generate          

      - name: Deploy blog
        run: |
          git clone "https://${{ secrets.GH_REF }}" deploy_git
          mv ./deploy_git/.git ./public/
          cd ./public
          git config --local user.email "bravohex@gmail.com" # 你的邮箱
          git config --local user.name "codewindy" # 你的用户名
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" master:master          
